const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = process.env.SIMULATOR_TEST_ROOT || path.join(__dirname,'..');
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const css = fs.readFileSync(path.join(root,'styles.css'),'utf8');
const apply = app.match(/function applyCase\(value\) \{[\s\S]*?\n\}/)[0];
const ctx = vm.createContext({});
vm.runInContext(apply,ctx);
for (const name of ['Amy','AMY','amy','小Amy']) assert.equal(vm.runInContext('applyCase('+JSON.stringify(name)+')',ctx),name);
assert.ok(!html.includes('id="case-options"') && !html.includes('id="case-field"'));
assert.ok(!app.includes('getElementById("case-options")') && !app.includes('getElementById("case-field")'));
assert.ok(html.includes('英文大小寫將依照您的輸入呈現。'));
assert.match(app,/zhRounded: \{[\s\S]*?JinXuan Latte[\s\S]*?weight: "800"/);
assert.ok(css.includes('assets/fonts/jf-jinxuanlatte-3.0-extrabold.otf'));
assert.ok(fs.statSync(path.join(root,'assets/fonts/jf-jinxuanlatte-3.0-extrabold.otf')).size>1000000);
console.log('PASS: preserve input case, removed controls, ExtraBold font asset and selection.');
